### ISSUE TITLE
Counter metrics are being added instead of replaced

### ISSUE THREAD

**Issue by marcosnils** [prometheus/statsd_exporter#122]
I have a statsd producer that's emitting a constant `counter` type metric

i.e:

```
myhost.myexec.http.status.404.count:2329|c
myhost.myexec.http.status.200.count:30|c
myhost.myexec.http.status.304.count:10|c
```

Because the metric is a `counter` in the origin system, if I don't get any requests during the scraping period, it'll send again the same value the next time.

I've added the following mapping in my statsd_exporter to use prometheus dimentions like this:

```yaml
mappings:
- match: ^([^.]*)\.([^.]*)--http.status.([^.]*).count
  match_type: "regex"
  name: "http_status_count"
  labels:
    code: "$3"
```

So the ending metric is something like: 
```
http_status_count{code="200"} 1557
http_status_count{code="304"} 18
http_status_count{code="404"} 6987
```

What's happening is that statsd_exporter is constantly *adding* the values that the origin is pushing even though they don't change. So what I end up seing in the prometheus metrics is a constant increment even though the metrics don't change. 

Any ideas?
