### ISSUE TITLE
Error during metrics mapping: "<Metric> should be a Counter"

### ISSUE THREAD

**Issue by InKolev** [prometheus/statsd_exporter#128]
Hi, 

I received the following error during my **statsd->statsd_exporter integration**.
It seems like if I'm using **counters in my Statsd Client**, the mappings work fine, but if I use **gauges or timers**, it doesn't.
I didn't manage to find in the documentation any **extra configurations** that I need to add to the mappings in order for statsd_exporter to identify what is the type of the metric and map it to the appropriate Prometheus-type metric.
I will appreciate any assistance, since I am kind of stuck with this.

## Errors
```
2 error(s) occurred:
* collected metric statsd label:<name:"action" value:"CheckHealthAsync" > label:<name:"application" value:"TestMicroservice" > label:<name:"host" value:"DESKTOP_KASLMVQ" > label:<name:"metric" value:"HealthStatus" > gauge:<value:10 >  **should be a Counter**
* collected metric statsd label:<name:"action" value:"StartAction" > label:<name:"application" value:"TestMicroservice" > label:<name:"host" value:"DESKTOP_KASLMVQ" > label:<name:"metric" value:"MetricGauge" > gauge:<value:10 >  **should be a Counter**
```

## Mappings
```
--- 
mappings: 
  - 
    labels: 
      action: $3
      application: $2
      host: $1
      metric: $4
    match: "*.*.*.*"
    name: statsd_exporter
```
