### ISSUE TITLE
Mapping not working

### ISSUE THREAD

**Issue by guillaumeger** [prometheus/statsd_exporter#209]
I have the following metric in statsd:
![statsd](https://user-images.githubusercontent.com/7086664/57235081-18c66480-6ff0-11e9-8aad-372117cb83f3.png)

I make a mapping as such:
```
    mappings:
    - match: application.*.screeneditor.*.request-time.unknown.count
      name: "screeneditor_request_time_unknown_count"
      labels:
        env: "$1"
        service: "$2"
```
The mapping does not work:
```
/ # wget localhost:9102/metrics
Connecting to localhost:9102 (127.0.0.1:9102)
metrics              100% |*********************************************************************************************************************************| 65319  0:00:00 ETA
/ # grep screeneditor_request_time_unknown_count metrics
/ # grep mapping metrics
# HELP statsd_exporter_events_unmapped_total The total number of StatsD events no mapping was found for.
# HELP statsd_exporter_loaded_mappings The current number of configured metric mappings.
# TYPE statsd_exporter_loaded_mappings gauge
statsd_exporter_loaded_mappings 1
/ # 
```
And I have the following metric in prometheus:
![statsd-prom](https://user-images.githubusercontent.com/7086664/57235230-6d69df80-6ff0-11e9-90a7-e91ca40b93d8.png)

Am I missing something?

Thanks!
