### ISSUE TITLE
replace datadog client ，but some metrics are lost

### ISSUE THREAD

**Issue by rulai-zhuyi** [prometheus/statsd_exporter#248]
datadog server can receive follow metrics:
api.avg
api.medium
api.max

but promethues server can receive one follow metric
api

I use Metric Mapping and Configuration,as follow:
mappings:
- match: "*.*"
  name: "${1}_${2}"
  label:
    transition: "dog2pro"
- match: "*.*.*"
  name: "${1}_${2}_${3}"
  label:
    transition: "dog2pro"
- match: "*.*.*.*"
  name: "${1}_${2}_${3}_${4}"
  label:
    transition: "dog2pro"

but it is Little effect

**Comment by rulai-zhuyi** [comment]
mappings:
- match: "*.*"
  name: "${1}_${2}"
  label:
    transition: "dog2pro"
- match: "*.*.*"
  name: "${1}_${2}_${3}"
  label:
    transition: "dog2pro"
- match: "*.*.*.*"
  name: "${1}_${2}_${3}_${4}"
  label:
    transition: "dog2pro"

**Comment by rulai-zhuyi** [comment]
PS: the Mapping and Configuration's "*" is filter by github

**Comment by matthiasr** [comment]
Please wrap the config snippets in triple backticks, that makes them show
in full.

**Comment by rulai-zhuyi** [comment]
this is my Mapping and Configuration
`mappings:
- match: "*.*"
  name: "${1}_${2}"
  label:
    transition: "dog2pro"
- match: "*.*.*"
  name: "${1}_${2}_${3}"
  label:
    transition: "dog2pro"
- match: "*.*.*.*"
  name: "${1}_${2}_${3}_${4}"
  label:
    transition: "dog2pro"`

**Comment by rulai-zhuyi** [comment]
this is my Mapping and Configuration

<<<
mappings:
- match: "*.*"
  name: "${1}_${2}"
  label:
    transition: "dog2pro"
- match: "*.*.*"
  name: "${1}_${2}_${3}"
  label:
    transition: "dog2pro"
- match: "*.*.*.*"
  name: "${1}_${2}_${3}_${4}"
  label:
    transition: "dog2pro"

>>>

**Comment by rulai-zhuyi** [comment]
this is my Mapping and Configuration
 ```
mappings:
- match: "*.*"
  name: "${1}_${2}"
 label:
    transition: "dog2pro"
- match: "*.*.*"
  name: "${1}_${2}_${3}"
  label:
    transition: "dog2pro"
- match: "*.*.*.*"
  name: "${1}_${2}_${3}_${4}"
  label:
    transition: "dog2pro"
```

**Comment by matthiasr** [comment]
What is the type of these metrics? Are these really separate metrics, or aggregations over event observations? In Prometheus, these are aggregated _differently_ (either as summaries or as histograms, depending on your configuration; histograms are preferred).

**Comment by rulai-zhuyi** [comment]
three metrics type is  gauge,  These are separate metrics
My prometheus's config is default

**Comment by rulai-zhuyi** [comment]
sorry, in fact service push to datadog client is  one metric() ,type is  histograms, in datadog server is decompose to sevaral metrics ,such as(api.avg,api.mediun,api,max etc.)
but in prometheus server only on metric , can you tell me how to change prometheus's config  to support it .

**Comment by matthiasr** [comment]
There are a few issues with your mapping config. The indentation is off; I assume that this is a copy-past issue since it prevents the config from loading as is. If I straighten that out, the label isn't getting attached because the key needs to be `labels` not `label`.

Additionally, the example metric you gave (`api`) won't be matched by your mappings at all.

Now, with this configuration:

```
mappings:
- match: "*.*"
  name: "${1}_${2}"
  labels:
    transition: "dog2pro"
- match: "*.*.*"
  name: "${1}_${2}_${3}"
  label:
    transition: "dog2pro"
- match: "*.*.*.*"
  name: "${1}_${2}_${3}_${4}"
  label:
    transition: "dog2pro"
```

I get this:

```
[I] ~/s/g/p/statsd_exporter (master|✔) $ curl http://localhost:9102/metrics | fgrep song
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7597    0  7597    0     0  1289k      0 --:--:-- --:--:-- --:--:-- 1483k
[I] ~/s/g/p/statsd_exporter (master|✔) [1] $ echo 'song.length:240|h' | nc localhost 9125
[I] ~/s/g/p/statsd_exporter (master|✔) $ curl http://localhost:9102/metrics | fgrep song
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8448    0  8448    0     0  1412k      0 --:--:-- --:--:-- --:--:-- 1650k
# HELP song_length Metric autogenerated by statsd_exporter.
# TYPE song_length summary
song_length{transition="dog2pro",quantile="0.5"} 0.24
song_length{transition="dog2pro",quantile="0.9"} 0.24
song_length{transition="dog2pro",quantile="0.99"} 0.24
song_length_sum{transition="dog2pro"} 0.24
song_length_count{transition="dog2pro"} 1
```

Note that the exporter treats "histogram" basically the same as a "timer" event in pure statsd – both represent the observation of an event. By default, for now, the exporter produces Prometheus _summaries_ with precomputed quantiles, you may want to set `timer_type: histogram` instead:

```
defaults:
  timer_type: histogram
  buckets: [ 0.01, 0.1, 0.2, 0.3, 0.5, 1.0, 5.0, 10.0 ]
mappings:
- match: "*.*"
  name: "${1}_${2}"
  labels:
    transition: "dog2pro"
```
```
[I] ~/s/g/p/statsd_exporter (master|✔) $ echo 'song.length:240|h' | nc localhost 9125
[I] ~/s/g/p/statsd_exporter (master|✔) $ curl http://localhost:9102/metrics | fgrep song
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8754    0  8754    0     0  1422k      0 --:--:-- --:--:-- --:--:-- 1709k
# HELP song_length Metric autogenerated by statsd_exporter.
# TYPE song_length histogram
song_length_bucket{transition="dog2pro",le="0.01"} 0
song_length_bucket{transition="dog2pro",le="0.1"} 0
song_length_bucket{transition="dog2pro",le="0.2"} 0
song_length_bucket{transition="dog2pro",le="0.3"} 1
song_length_bucket{transition="dog2pro",le="0.5"} 1
song_length_bucket{transition="dog2pro",le="1"} 1
song_length_bucket{transition="dog2pro",le="5"} 1
song_length_bucket{transition="dog2pro",le="10"} 1
song_length_bucket{transition="dog2pro",le="+Inf"} 1
song_length_sum{transition="dog2pro"} 0.24
song_length_count{transition="dog2pro"} 1
```

In Prometheus, the calculation of median/average/percentiles over histograms happens at query time, that way it can be aggregated by whichever dimensions you need then.

Since the exporter is working as I expect it to, I'm going to close this issue. Please refer to the [community page](https://prometheus.io/community/) for usage questions.
