### ISSUE TITLE
Regex example not working

### ISSUE THREAD

**Issue by salvaforadada** [prometheus/statsd_exporter#274]
Hello, I have tried to run a docker container using as statsd mapping configuration file the one that you propose for the regex example:

```yaml
mappings:
- match: "test\.(\w+)\.(\w+)\.counter"
  match_type: regex
  name: "${2}_total"
  labels:
    provider: "$1"
```
and it fails, logging the following error:
```level=fatal msg="Error loading config:yaml: line 2: found unknown escape character" source="main.go:245"```

I thought it was a GO issue because of the "\\" characters used in the regex chain, so I scaped them using double "\\". However, although the container starts, the regex does not work, because it does not catch what it is supposed to catch. 

Could you please help me with this issue? Thanks in advance.

**Comment by matthiasr** [comment]
Thank you! I haven't had time to test myself yet. I suspect this might be a YAML issue, can you try a different [quoting style](https://yaml-multiline.info/)? I have high hopes for single quotes like

```yaml
mappings:
- match: 'test\.(\w+)\.(\w+)\.counter'
  match_type: regex
  name: "${2}_total"
  labels:
    provider: "$1"
```

**Comment by xocasdashdash** [comment]
Yeah, i can confirm it is, this also works correctly: 
```yaml
mappings:
- match: "test\\.(\\w+)\\.(\\w+)\\.counter"
   match_type: regex
   name: "${2}_total"
```
