### ISSUE TITLE
FR: Option to remap labels

### ISSUE THREAD

**Issue by SuperQ** [prometheus/statsd_exporter#296]
Sometimes applications send statsd tags that are sub-optimal. For example, Sentry in [DogStatsD mode](https://docs.sentry.io/server/internal-metrics/#dogstatsd-backend) produces an `instance` label. IIRC you can't fix this in `metric_relabel_configs`.

Having a way to remap label names on ingesting would be useful.

**Comment by brian-brazil** [comment]
> IIRC you can't fix this in metric_relabel_configs.

That doesn't sound right.

**Comment by SuperQ** [comment]
I figured out what the issue was with the relabel.

```yaml
metric_relabel_configs:
- source_labels:
  - exported_instance
  target_label: foo
```

It might still be useful to do this mapping in the exporter, to avoid the need for relabel configs, and do more custom changes.

Something like this:
```yaml
mappings:
- match: "something.*.*.*"
  remap:
    instance: foo
- match: "othermetric.*.*.*"
  remap:
    ambiguous_name: bar
```
