### ISSUE TITLE
glob takes precedence over regex, bug or design?

### ISSUE THREAD

**Issue by faja** [prometheus/statsd_exporter#349]
I'm sending `job.fetch_duration_seconds:1.000000|ms` to a `statsd_exporter` running with below's mapping config:
```
mappings:
- match: ([^.]+)\.([^.]+)
  match_type: regex
  name: $2
  observer_type: histogram
  labels:
    job: $1
- match: "*.*"
  name: $2
  labels:
    job: $1
```
The metric line is caught by the second (`glob`) rule, not the first one (`regex`), and the `summary` is created (not the `histogram` - as I would expect).

Is it a bug or design that `glob` rules always takes precedence over `regex` ones?
