### ISSUE TITLE
Enable more linters

### ISSUE THREAD

**Issue by glightfoot** [prometheus/statsd_exporter#364]
Is there any interest in enabling some additional linters in the `.golangci.yml` file? I think it would help clean some things up, make the code a little more approachable, and also point out a few areas where things aren't working as intended. There's some dead code and some metrics that aren't being used that could be easily picked up.

My standard `.golangci.yml` file looks like this, any thoughts on adding some of these?

```
run:
  tests: true
  modules-download-mode: vendor
  skip-dirs:
  - vendor
linters:
  disable-all: true
  enable:
  - deadcode
  - goimports
  - gosimple
  - govet
  - ineffassign
  - nakedret
  - staticcheck
  - structcheck
  - unused
  - varcheck
  - whitespace
linters-settings:
  govet:
    check-shadowing: true
issues:
  exclude-use-default: false
  exclude:
  - 'shadow: declaration of "err" shadows declaration at line (\d+)'
  max-issues-per-linter: 0
  max-same-issues: 0
```
