### ISSUE TITLE
Container doesn't start

### ISSUE THREAD

**Issue by radiantone** [prometheus/statsd_exporter#416]
Attaching to statsd
statsd            | statsd_exporter: error: unknown short flag '-s', try --help
statsd exited with code 1

**Comment by matthiasr** [comment]
What is the command line that you used? Keep in mind that all core Prometheus projects use POSIX-style flags with two dashes for the long form flags

**Comment by radiantone** [comment]
Just trying to run it from docker compose
```
  statsd:
    container_name: statsd
    image: prom/statsd_exporter
    command: "-statsd.mapping-config=/tmp/statsd_mapping.conf"
    ports:
      - "9102:9102"
      - "9125:9125/udp"
    volumes:
      - "./statsd.conf:/tmp/statsd_mapping.conf"
```
