### ISSUE TITLE
"Bad line from StatsD" message when sending metrics

### ISSUE THREAD

**Issue by leanvargas** [prometheus/statsd_exporter#439]
Hi,
I have been trying to send metrics to the exporter but I always get the same error.
This is what I have been doing:

`statsd_mapping.yml`
```yaml
mappings:
- match: "test.dispatcher.*.*.*"
  name: "dispatcher_events_total"
  labels:
    processor: "$1"
    action: "$2"
    outcome: "$3"
    job: "test_dispatcher"
- match: "*.signup.*.*"
  name: "signup_events_total"
  labels:
    provider: "$2"
    outcome: "$3"
    job: "${1}_server"
```

```bash
docker run --rm -p 9102:9102 -p 9125:9125 -p 9125:9125/udp \
        -v $PWD/statsd_mapping.yml:/tmp/statsd_mapping.yml \
        prom/statsd-exporter --statsd.mapping-config=/tmp/statsd_mapping.yml --log.level=debug
```

sending data:
```bash
echo 'test.dispatcher.FooProcessor.send.success'|nc -u 10.2.206.199 9125
```

and the output of the container shows:
```
level=debug ts=2022-06-10T17:47:14.537Z caller=listener.go:75 msg="Incoming line" proto=udp line=X
level=debug ts=2022-06-10T17:47:14.538Z caller=line.go:214 msg="Bad line from StatsD" line=X
level=debug ts=2022-06-10T17:47:14.538Z caller=listener.go:75 msg="Incoming line" proto=udp line=X
level=debug ts=2022-06-10T17:47:14.538Z caller=line.go:214 msg="Bad line from StatsD" line=X
level=debug ts=2022-06-10T17:47:14.538Z caller=listener.go:75 msg="Incoming line" proto=udp line=X
level=debug ts=2022-06-10T17:47:14.538Z caller=line.go:214 msg="Bad line from StatsD" line=X
level=debug ts=2022-06-10T17:47:14.538Z caller=listener.go:75 msg="Incoming line" proto=udp line=X
level=debug ts=2022-06-10T17:47:14.538Z caller=line.go:214 msg="Bad line from StatsD" line=X
```

I have tried several mapping configuration and neither of them worked. Am I doing something wrong?

**Comment by pedro-stanaka** [comment]
You are sending a invalid [statsd line](https://github.com/statsd/statsd#usage) that is why you are seeing this message. Check the correct format in the link.

**Comment by leanvargas** [comment]
I tried sending
```
echo 'test.dispatcher.FooProcessor.send.success:1|c' |nc -u 10.2.206.199 9125
```
and got the same error. Then I changed the mapping file to:
```yaml
mappings:
- match: "*"
  name: "test"
```
and sent:
```
echo "foo:1|c" | nc -u -w0 127.0.0.1 9125
```
but the error continues.
