### ISSUE TITLE
how to map datadog label?

### ISSUE THREAD

**Issue by pindge** [prometheus/statsd_exporter#462]
```
  # trials
  - match: "pin\.datacube\.index:0\|g\|#app:(.*),action:(.*),pod:(.*)\.(.*)"
    name: "pin_mimic_datacube_index"
    match_metric_type: gauge
    match_type: regex
    labels:
      app: "$1"
      action: "$2"
      pod_1: "$3"
      pod_2: "$4"
```
following: https://docs.datadoghq.com/developers/dogstatsd/datagram_shell/?tab=metrics#python-3
```
>>> import socket
>>> sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM) # UDP
>>> sock.sendto(b"pin.datacube.index:60|g|#app:s3-to-dc,action:test,pod:abc.12121", ("localhost", 8125))
```

result 

```
pin_datacube_index{action="test",app="s3-to-dc",pod="abc.12121"} 60
# HELP pin_mimic_datacube_index Metric autogenerated by statsd_exporter.
# TYPE pin_mimic_datacube_index gauge
pin_mimic_datacube_index{action="",app="",pod_1="",pod_2=""} 0
```
