### ISSUE TITLE
bug: Configuration reload does not affect bucket configuration

### ISSUE THREAD

**Issue by pedro-stanaka** [prometheus/statsd_exporter#471]
## Bug description

**What is happening?**

1. I start the exporter with a mapping configuration (see example config at the end).
2. I send some samples of the metric constantly (before metric had chance to churn)
3. I change mapping configuration and update the bucked layout for my metrics
4. I trigger a reload via sighup/web lifecycle
5. After sending new samples, old bucket configuration is still present and not new, updated one.

This is happening because the metric is never deleted after the reload from the `Registry`.

**What you expected to happen?**

On step `5.` I would expect the new bucket configuration to take place.

### Notes

Example config:

```
defaults:
    ttl: 3m
    match_type: regex
    observer_type: histogram
    histogram_options:
        buckets: [0.1, 0.25, 150, 500, 900]
mappings:
    - match: \bexample_metric\b
      observer_type: histogram
      histogram_options:
        buckets: [10, 40, 50, 80, 100, 120, 150, 200, 250]
      name: example_metric
      labels:
        statsd_exporter_config_mapping: "true"
```
