### ISSUE TITLE
Support prefixed glob matches

### ISSUE THREAD

**Issue by matschaffer-roblox** [prometheus/statsd_exporter#481]
I'm transition from https://docs.victoriametrics.com/vmagent.html to https://github.com/prometheus/graphite_exporter and ran into a case where I'm using prefixed globs to help distinguish from one of a few possible metric prefix cases.

Here's a simple example match:

```
- match: "prefixed_glob.prefix_*.*"
  name: prefixed_glob
  labels:
    prefix: "${1}"
    metric: "${2}"
```

This will fail with:

```
invalid match: prefixed_glob.prefix_*.*
```

I think I could maybe switch to regex matches, but I'll need 10 of them so I'm a little concerned with the possible overhead vs glob matching.

It'd be great if the statsd exporter mapper could handle prefixed globs, or if you suspect 10 regex matches is no big deal, let me know :)
