### ISSUE TITLE
Feature Request: "scale" field in mapping config to convert units

### ISSUE THREAD

**Issue by ebracho** [prometheus/statsd_exporter#498]
For my use case it would be great if there was a `scale` field in the mapping config to allow converting metric values from non-base units (e.g. milliseconds, microseconds) to base units. [As per prometheus best practices](https://prometheus.io/docs/practices/naming/): 

> A metric name ...should use base units (e.g. seconds, bytes, meters - not milliseconds, megabytes, kilometers). 

Ex:

```yaml
mappings:
  - match: statsd.grpc_server.*.*.latency_us
    name: grpc_server_handling_seconds
    scale: 1e-6 # converts microseconds -> seconds
    labels:
      grpc_service: "${1}"
      grpc_method: "${2}"
```
