### ISSUE TITLE
metric name should be split from labels in yaml mapping format

### ISSUE THREAD

**Issue by drawks** [prometheus/statsd_exporter#90]
#66 was recently merged and I'm a huge fan of the new yaml mappings, however I think it is probably a bad idea to have the `name` label have magic behavior in setting the metric name in the exporter. I /think/ it probably makes more sense to have a `metric_name` parameter one level higher in the mapper config. This should disambiguate the result of the mapping AND allow for, if desired, a mapping which sets a label called `name`.

Proposed change...
this:
```
mappings:
- match: test.case.*
  labels:
    name: "test_case_total"
    blargle: "$1"
```
Would become this:
```
mappings:
- match: test.case.*
  metric_name: "test_case_total"
  labels:
    blargle: "$1"
```
